---
functional:
  - У пользователя должна быть возможность зарегистрироваться через email, GitHub или Discord
  - У пользователя должна быть возможность авторизоваться через email, GitHub или Discord.
  - У пользователя должна быть возможность выбора игры против рандомного соперника, друга или бота.
  - Пользователь должен иметь возможность посмотревать статистики своих игр.
  - Пользователь должен иметь возможность выбирать уровень сложности, тип игры, временные рамки и задачу в игре.
  - Пользователь должен иметь возможность выбрать язык программирования для задачи.
  - Пользователь должен иметь возможность выбрать язык программирования для профиля.
  - У пользователя должена быть возможность сдаться.
  - Пользователь должен иметь возможность просмотреть личный рейтинг
  - Сайт должен отображать рейтинг игроков.
  - Пользователя может посмотривать статистику других игроков.
  - У пользователя должна быть возможность посмотреть информиацию о своих прошлых играх.
  - У пользователя должна быть возможность возможность создавать турниры.
  - У пользователя должна быть возможность общаться в чате с соперником.
  - У пользователя должна быть возможность присоединиться к созданной другим участником игре или турниру  ???
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен быть интуитивно понятен.
  - Все атрибуты сайта должны быть выполнены кооректно сверстаны, никакой из элементов не должен вылезать из своих границ.
  - Победа должна присваиваться игроку который верно решил задачу первым.
