---
functional:
  - У пользователя должна быть возможность зарегистрироваться через email, GitHub или Discord
  - У пользователя должна быть возможность авторизоваться через email, GitHub или Discord.
  - Пользователь должен иметь возможность создания игры "Create a game".???
  - У пользователя должна быть возможность выбора игры против рандомного соперника, друга или бота.
  - Пользователь должен иметь возможность выбирать уровень сложности, тип игры, временные рамки и задачу в игре.
  - Пользователь должен иметь возможность просматривать статистики своих игр.
  - Пользователь должен иметь возможность выбрать язык программирования для задачи.
  - Каждый игрок должен видеть задание.
  - Каждый игрок должен видеть код своего соперника в режиме онлайн.
  - Побеждает тот игрок, чей код первым пройдет все тесты.
  - У пользователя должена быть возможность сдаться.
  - У играков неограниченное количество проверок своего решения.
  - В случае отключения одного из игроков от игровой сессии, второй игрок должен иметь возможность продолжить игру без прерывания.
  - Если игрок теряет соединение во время игры, он должен иметь возможность повторно подключиться к той же игровой сессии в любой момент до её завершения.
  - Пользователь должен иметь возможность просмотреть личный рейтинг
  - Сайт должен отображать рейтинг других игроков.
  - На сайте должны отображаться имена играков.
  - Пользователя может посмотривать статистику других игроков.
  - У пользователя должна быть возможность создавать турниры.
  - У пользователя должна быть возможность общаться в чате с соперником.
  - Игроки могут общаться со зрителями в чате.
  - На сайте можно следить за игрой других играков в реальном времени.
  - В настройках профиля пользователь может изменить – имя, язык программирования, тип звука, уровень громкости звука, а также может привязать другие аккаунты (GitHub, Discord).
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
implicit:
  - Сайт должен быть интуитивно понятен.
  - Пользователь должен иметь возможность редактировать свой профиль.
  - Система должна предоставлять пользователю возможность сыграть пробную игру без обязательной регистрации аккаунта.
  - Игрок имеет доступ только к своему редактору кода и не может изменять код другого игрока.
  - Зрители не имеют доступа к редакторам кода участников и не могут изменять их код.
  - Условия задачи игры, предоставленные перед началом, не могут быть изменены игроками.
  - В игровом редакторе кода для каждого языка программирования должен быть представлен соответствующий шаблон.
  - Начисление и списание очков рейтинга зависят от рейтинга оппонентов и сложности игры, для ботов изменения рейтинга не применяются.
  - Таблица лидеров должна обновляться автоматически на основе игровых результатов, без возможности ручного внесения изменений пользователями.
  - Пользователь может сбросить пароль от аккаунта.
  - Пользователь может выполнить выход из аккаунта.
